# Generated by Django 4.2.7 on 2026-09-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed explanation of work completed to resolve the issue.')),
                ('remarks', models.TextField(blank=True, help_text='Operational remarks or maintenance recommendations.')),
                ('resolution_proof', models.ImageField(blank=True, help_text='Proof photo after resolution', null=True, upload_to='resolutions/images/%Y/%m/')),
                ('resolution_document', models.FileField(blank=True, help_text='Work order, inspection sheet, or sign-off document', null=True, upload_to='resolutions/docs/%Y/%m/')),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Admin Verification'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Rejected (Requires Re-work)')], default='APPROVED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='complaints.complaint')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_resolutions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolution',
                'verbose_name_plural': 'Resolutions',
                'ordering': ['-resolved_at'],
            },
        ),
    ]
