# Generated by Django 4.2.7 on 2026-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Temporary Registration',
                'verbose_name_plural': 'Temporary Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
