# Generated by Django 4.2.7 on 2026-09-29 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_temporaryregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
