# Generated by Django 4.2.7 on 2026-09-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, unique=True)),
                ('resolution_deadline_hours', models.PositiveIntegerField(help_text='Hours allowed before SLA breach')),
                ('level1_warning_hours', models.PositiveIntegerField(default=12, help_text='Hours before deadline to issue warning alert')),
                ('escalation_level_2_target', models.CharField(default='DEPARTMENT_HEAD', max_length=50)),
                ('escalation_level_3_target', models.CharField(default='ADMINISTRATOR', max_length=50)),
                ('escalation_level_4_target', models.CharField(default='HIGHER_AUTHORITY', max_length=50)),
            ],
            options={
                'verbose_name': 'SLA Escalation Rule',
                'verbose_name_plural': 'SLA Escalation Rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Field Staff'), (2, 'Level 2 - Department Head'), (3, 'Level 3 - System Administrator'), (4, 'Level 4 - Higher Civic Authority')], default=2)),
                ('reason', models.TextField()),
                ('is_automated', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='complaints.complaint')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalation Log',
                'verbose_name_plural': 'Escalation Logs',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
