# Generated by Django 4.2.7 on 2026-09-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/%Y/%m/')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff note: hidden from citizen, visible only to Staff and Admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='complaints.complaint')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaint_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Message',
                'verbose_name_plural': 'Complaint Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
