# Generated by Django 4.2.7 on 2026-09-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ - Excellent (5/5)'), (4, '★★★★☆ - Good (4/5)'), (3, '★★★☆☆ - Average (3/5)'), (2, '★★☆☆☆ - Poor (2/5)'), (1, '★☆☆☆☆ - Very Poor (1/5)')], default=5)),
                ('satisfaction_level', models.CharField(choices=[('VERY_SATISFIED', 'Very Satisfied'), ('SATISFIED', 'Satisfied'), ('NEUTRAL', 'Neutral'), ('DISSATISFIED', 'Dissatisfied'), ('VERY_DISSATISFIED', 'Very Dissatisfied')], default='SATISFIED', max_length=30)),
                ('resolution_quality', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], default='GOOD', max_length=30)),
                ('comments', models.TextField(blank=True, help_text='Feedback comments on resolution speed and officer conduct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizen Feedback',
                'verbose_name_plural': 'Citizen Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
